### ISSUE TITLE
AGPL?

### ISSUE THREAD

**Issue by davelab6** [byte-foundry/genese.ptf#1]
This repo is still AGPL; is this intentional? I recommend the OFL for the font data, so that it can be used with the 100s of existing OFL fonts  :)

**Comment by louisremi** [comment]
AGPL is a bad choice, as we want to allow designers to choose how they license the fonts they produce using Prototypo. We'll replace it with CC-BY right now.

**Comment by davelab6** [comment]
I recommend CC-0 in this case :)

**Comment by davelab6** [comment]
:+1:
